import type { RepetitionRecord } from '../fsm/types.js';

export interface FatigueMarker {
  timestampMs: number;
  repIndex: number;
  type: 'TEMPO_SLOWDOWN' | 'FORM_DEGRADATION' | 'ASYMMETRY_INCREASE';
  description: string;
}

export interface FatigueAnalysisResult {
  totalReps: number;
  validReps: number;
  invalidReps: number;
  formAccuracyPercent: number;
  averageRepDurationMs: number;
  tempoSlowdownFactor: number;
  fatigueDetected: boolean;
  fatigueOnsetTimestampMs?: number;
  fatigueOnsetRepIndex?: number;
  fatigueMarkers: FatigueMarker[];
}

/**
 * Analyzes session repetition history to identify fatigue breakdown markers,
 * tempo slowdown, and form degradation timestamps.
 *
 * @param repHistory - Array of RepetitionRecords generated by ExerciseFSM
 * @returns FatigueAnalysisResult
 */
export function detectFatigueBreakdown(repHistory: RepetitionRecord[]): FatigueAnalysisResult {
  const totalReps = repHistory.length;
  if (totalReps === 0) {
    return {
      totalReps: 0,
      validReps: 0,
      invalidReps: 0,
      formAccuracyPercent: 100.0,
      averageRepDurationMs: 0,
      tempoSlowdownFactor: 1.0,
      fatigueDetected: false,
      fatigueMarkers: [],
    };
  }

  const validReps = repHistory.filter((r) => r.isValid).length;
  const invalidReps = totalReps - validReps;
  const formAccuracyPercent = Math.round((validReps / totalReps) * 1000) / 10;

  const totalDurationSum = repHistory.reduce((sum, r) => sum + r.durationMs, 0);
  const averageRepDurationMs = Math.round(totalDurationSum / totalReps);

  // Compute tempo slowdown (first 3 reps vs last 3 reps)
  let tempoSlowdownFactor = 1.0;
  if (totalReps >= 4) {
    const earlyReps = repHistory.slice(0, Math.min(3, Math.floor(totalReps / 2)));
    const lateReps = repHistory.slice(-Math.min(3, Math.floor(totalReps / 2)));

    const earlyAvgDuration = earlyReps.reduce((s, r) => s + r.durationMs, 0) / (earlyReps.length || 1);
    const lateAvgDuration = lateReps.reduce((s, r) => s + r.durationMs, 0) / (lateReps.length || 1);

    if (earlyAvgDuration > 0) {
      tempoSlowdownFactor = Math.round((lateAvgDuration / earlyAvgDuration) * 100) / 100;
    }
  }

  const fatigueMarkers: FatigueMarker[] = [];
  let fatigueOnsetTimestampMs: number | undefined = undefined;
  let fatigueOnsetRepIndex: number | undefined = undefined;

  // Detect form degradation points
  for (let i = 0; i < repHistory.length; i++) {
    const rep = repHistory[i];
    if (!rep) continue;

    // Asymmetry warning
    if (rep.maxAsymmetryDeg > 12.0) {
      fatigueMarkers.push({
        timestampMs: rep.timestampMs,
        repIndex: rep.repIndex,
        type: 'ASYMMETRY_INCREASE',
        description: `Bilateral asymmetry elevated (${rep.maxAsymmetryDeg}° asymmetry)`,
      });

      if (!fatigueOnsetTimestampMs) {
        fatigueOnsetTimestampMs = rep.timestampMs;
        fatigueOnsetRepIndex = rep.repIndex;
      }
    }

    // Invalid rep breakdown
    if (!rep.isValid) {
      fatigueMarkers.push({
        timestampMs: rep.timestampMs,
        repIndex: rep.repIndex,
        type: 'FORM_DEGRADATION',
        description: `Form failure at rep ${rep.repIndex} (${rep.invalidReason ?? 'Invalid ROM'})`,
      });

      if (!fatigueOnsetTimestampMs) {
        fatigueOnsetTimestampMs = rep.timestampMs;
        fatigueOnsetRepIndex = rep.repIndex;
      }
    }
  }

  // Tempo slowdown marker
  const lastRep = repHistory[repHistory.length - 1];
  if (tempoSlowdownFactor >= 1.35 && lastRep) {
    fatigueMarkers.push({
      timestampMs: lastRep.timestampMs,
      repIndex: lastRep.repIndex,
      type: 'TEMPO_SLOWDOWN',
      description: `Movement tempo degraded by ${Math.round((tempoSlowdownFactor - 1) * 100)}% due to muscular fatigue`,
    });
  }

  const fatigueDetected = fatigueMarkers.length > 0 || tempoSlowdownFactor >= 1.35;

  return {
    totalReps,
    validReps,
    invalidReps,
    formAccuracyPercent,
    averageRepDurationMs,
    tempoSlowdownFactor,
    fatigueDetected,
    fatigueOnsetTimestampMs,
    fatigueOnsetRepIndex,
    fatigueMarkers,
  };
}
